In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier

import warnings
warnings.filterwarnings('ignore')

In [6]:
df = pd.read_csv('../data/crop_recommendation.csv')

In [7]:
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  80  43  39    20.879744  82.002744  6.502985  202.935536  rice
1  79  55  38    21.770462  80.319644  7.038096  226.655537  rice
2  79  42  43    23.004459  82.320763  7.840207  263.964248  rice
3  75  42  37    26.491096  80.158363  6.980401  242.864034  rice
4  82  43  36    20.130175  81.604873  7.628473  262.717340  rice

In [8]:
df.tail()

        N   P   K  temperature   humidity        ph    rainfall   label
2195  106  15  25    26.774637  66.413269  6.780064  177.774507  coffee
2196  116  23  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  105  39  34    24.131797  67.225123  6.362608  173.322839  coffee
2198  102  15  31    26.272418  52.127394  6.758793  127.175293  coffee
2199   83  30  32    23.603016  60.396475  6.779833  140.937041  coffee

In [9]:
df.size

17600

In [10]:
df.shape

(2200, 8)

In [11]:
df.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='object')

In [12]:
df['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [13]:
df.dtypes

N                int64
P                int64
K                int64
temperature    float64
humidity       float64
ph             float64
rainfall       float64
label           object
dtype: object

In [14]:
df['label'].value_counts()

label
rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: count, dtype: int64

SEPARATING FEATURES AND TARGET LABEL

In [15]:
features = df[['N', 'P','K','temperature', 'humidity', 'ph', 'rainfall']]
target = df['label']
#features = df[['temperature', 'humidity', 'ph', 'rainfall']]
labels = df['label']

In [16]:
# Initialzing empty lists to append all model's name and corresponding name
acc = []
model = []

In [17]:
# Splitting into train and test data

from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(features,target,test_size = 0.2,random_state =2)

RANDOM FOREST

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

RF = RandomForestClassifier(n_estimators=100, random_state=42)
RF.fit(Xtrain, Ytrain)

predicted_values = RF.predict(Xtest)

x = accuracy_score(Ytest, predicted_values)

print("RF Accuracy:", x)
print(classification_report(Ytest, predicted_values))

RF Accuracy: 0.9931818181818182
              precision    recall  f1-score   support

       apple       1.00      1.00      1.00        13
      banana       1.00      1.00      1.00        17
   blackgram       1.00      1.00      1.00        16
    chickpea       1.00      1.00      1.00        21
     coconut       1.00      1.00      1.00        21
      coffee       1.00      1.00      1.00        22
      cotton       1.00      1.00      1.00        20
      grapes       1.00      1.00      1.00        18
        jute       0.90      1.00      0.95        28
 kidneybeans       1.00      1.00      1.00        14
      lentil       1.00      1.00      1.00        23
       maize       1.00      1.00      1.00        21
       mango       1.00      1.00      1.00        26
   mothbeans       1.00      1.00      1.00        19
    mungbean       1.00      1.00      1.00        24
   muskmelon       1.00      1.00      1.00        23
      orange       1.00      1.00      1.00        29
      papaya       1.00      1.00      1.00        19
  pigeonpeas       1.00      1.00      1.00        18
 pomegranate       1.00      1.00      1.00        17
        rice       1.00      0.81      0.90        16
  watermelon       1.00      1.00      1.00        15

    accuracy                           0.99       440
   macro avg       1.00      0.99      0.99       440
weighted avg       0.99      0.99      0.99       440

In [19]:
# Cross validation score (Random Forest)
from sklearn.model_selection import cross_val_score
score = cross_val_score(RF, features, target, cv=5)
print(score)
print("Average Accuracy:", score.mean())

[0.99772727 0.99318182 0.99545455 0.99545455 0.99545455]
Average Accuracy: 0.9954545454545455

SAVING TRAINED MODEL

In [20]:
import os
import pickle

# Create models folder if not exists
os.makedirs('../models', exist_ok=True)

RF_pkl_filename = '../models/crop_model.pkl'

with open(RF_pkl_filename, 'wb') as file:
    pickle.dump(RF, file)

print("Model saved successfully!")

Model saved successfully!

MAKING A PREDICTION

In [21]:
data = np.array([[104,18, 30, 23.603016, 60.3, 6.7, 140.91]])
prediction = RF.predict(data)
print(prediction)

['coffee']

In [22]:
data = np.array([[83, 45, 60, 28, 70.3, 7.0, 150.9]])
prediction = RF.predict(data)
print(prediction)

['jute']